name: Update Port with YouTube Playlist Data
on:
  workflow_dispatch:
    inputs:
      playlistid:
        description: 'ID of the YouTube playlist'
        required: true
      port_context:
        description: 'Port context payload'
        required: true

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    env:
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jq for JSON processing
        run: sudo apt-get install jq

  fetch_playlist_metadata:
    runs-on: ubuntu-latest
    needs: setup_environment
    env:
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      PLAYLIST_ID: ${{ inputs.playlistid }}
    outputs:
      PLAYLIST_ID: ${{ steps.fetch_metadata.outputs.PLAYLIST_ID }}
      PLAYLIST_DATA: ${{ steps.fetch_metadata.outputs.PLAYLIST_DATA }}
    steps:
      - name: Generate Access Token
        id: token
        run: |
          response=$(curl -s -X POST "https://api.getport.io/v1/auth/access_token" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
            {
              "clientId": "$PORT_CLIENT_ID",
              "clientSecret": "$PORT_CLIENT_SECRET"
            }
EOF
          )
          ACCESS_TOKEN=$(echo "$response" | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Fetch YouTube Playlist Metadata
        id: fetch_metadata
        run: |
          playlist_response=$(curl -s "https://www.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails,status&id=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}")
          playlist_id=$(echo $playlist_response | jq -r '.items[0].id')
          playlist_data=$(echo $playlist_response | jq -c '.items[0] | {
            identifier: .id,
            title: .snippet.title,
            properties: {
              playlistId: .id,
              title: .snippet.title,
              description: .snippet.description,
              thumbnailUrl: .snippet.thumbnails.default.url,
              videoCount: .contentDetails.itemCount,
              created_at: .snippet.publishedAt
            }
          }')
          echo "PLAYLIST_ID=$playlist_id" >> $GITHUB_OUTPUT
          echo "PLAYLIST_DATA=$playlist_data" >> $GITHUB_OUTPUT

  push_playlist_to_port:
    runs-on: ubuntu-latest
    needs: fetch_playlist_metadata
    env:
      ACCESS_TOKEN: ${{ steps.token.outputs.ACCESS_TOKEN }}
    steps:
      - name: Push Playlist Data to Port
        run: |
          playlist_entity='${{ needs.fetch_playlist_metadata.outputs.PLAYLIST_DATA }}'
          response=$(curl -s -w "%{http_code}" -X POST "https://api.getport.io/v1/blueprints/playlist/entities?upsert=true" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$playlist_entity")
          if [[ "${response: -3}" != "200" && "${response: -3}" != "201" ]]; then
            echo "Failed to push playlist to Port. Response: $response"
            exit 1
          fi

  fetch_videos:
    runs-on: ubuntu-latest
    needs: [push_playlist_to_port, fetch_playlist_metadata]
    env:
      ACCESS_TOKEN: ${{ needs.fetch_playlist_metadata.outputs.ACCESS_TOKEN }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      PLAYLIST_ID: ${{ inputs.playlistid }}
    outputs:
      VIDEOS_ARRAY: ${{ steps.process_videos.outputs.VIDEOS_ARRAY }}
    steps:
      - name: Fetch and Process Videos
        id: process_videos
        run: |
          videos_array="[]"
          next_page_token=""
          while true; do
            playlist_items_url="https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}${next_page_token:+&pageToken=$next_page_token}"
            playlist_response=$(curl -s "$playlist_items_url")
            video_ids=$(echo "$playlist_response" | jq -r '.items[].snippet.resourceId.videoId')
            for video_id in $video_ids; do
              [ -z "$video_id" ] && continue
              video_details=$(curl -s "https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=$video_id&key=${YOUTUBE_API_KEY}")
              video_json=$(echo $video_details | jq -c '.items[0] | {
                identifier: .id,
                title: .snippet.title,
                properties: {
                  videoId: .id,
                  title: .snippet.title,
                  description: .snippet.description,
                  thumbnailUrl: .snippet.thumbnails.default.url,
                  duration: .contentDetails.duration,
                  viewCount: (.statistics.viewCount // "0" | tonumber),
                  likeCount: (.statistics.likeCount // "0" | tonumber),
                  commentCount: (.statistics.commentCount // "0" | tonumber)
                },
                relations: {
                  belongs_to_playlist: "'"${{ needs.fetch_playlist_metadata.outputs.PLAYLIST_ID }}"'"
                }
              }')
              videos_array=$(echo $videos_array | jq --argjson video "$video_json" '. + [$video]')
            done
            next_page_token=$(echo $playlist_response | jq -r '.nextPageToken // empty')
            [ -z "$next_page_token" ] && break
          done
          escaped_array=$(echo "$videos_array" | jq -R -s .)
          echo "VIDEOS_ARRAY=$escaped_array" >> $GITHUB_OUTPUT

  push_videos_to_port:
    runs-on: ubuntu-latest
    needs: fetch_videos
    env:
      ACCESS_TOKEN: ${{ needs.fetch_videos.outputs.ACCESS_TOKEN }}
    steps:
      - name: Push Videos to Port
        run: |
          videos_array='${{ needs.fetch_videos.outputs.VIDEOS_ARRAY }}'
          for video in $(echo "$videos_array" | jq -c '.[]'); do
            response=$(curl -s -w "%{http_code}" -X POST "https://api.getport.io/v1/blueprints/video/entities?upsert=true" \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$video")
            if [[ "${response: -3}" != "200" && "${response: -3}" != "201" ]]; then
              echo "Failed to push video to Port. Response: $response"
              exit 1
            fi
          done
